- Невозможно использовать с await (т.е. ожидать результата)
- Невозможно определить, когда выполнение завершится
- Вызывающий код не может перехватить возникающие исключения
Вывод: Везде, где доступно следует использовать async-Task вместо async void